export const MIX = {
  CONCRETE_DENSITY_G_PER_MM3: 0.0024,
  PLASTICIZER_PERCENT: 0.0075,
  WATER_CEMENT_RATIO: 0.44,
  CSA_PORTLAND_FRACTION: 0.50,
  CSA_FRACTION: 0.50,
  X33_DOSAGE_PERCENT: 0.0005,
  PIGMENT_MIN_PCT: 1,
  PIGMENT_MAX_PCT: 10,
  // AR glass fibers: 3% of cement weight — prevents cracking in large pieces
  FIBER_PERCENT: 0.03,
};
